!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  P1: 200.0
  P2: 400.0
  correlation_window_size: 131
  disp12MaxDiff: 0
  disparity_range: 128
  fullDP: false
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      P1: 200.0
      P2: 400.0
      correlation_window_size: 131
      disp12MaxDiff: 0
      disparity_range: 128
      fullDP: false
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      min_disparity: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      prefilter_cap: 31
      prefilter_size: 11
      speckle_range: 13
      speckle_size: 1000
      state: true
      stereo_algorithm: 0
      texture_threshold: 20
      type: ''
      uniqueness_ratio: 5.0
    state: []
  min_disparity: 0
  prefilter_cap: 31
  prefilter_size: 11
  speckle_range: 13
  speckle_size: 1000
  stereo_algorithm: 0
  texture_threshold: 20
  uniqueness_ratio: 5.0
state: []
